banks/urls.py
"""URL configuration for banks project."""

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('banks_app.urls')),
]

banks_app/urls.py
"""URL configuration for banks_app."""

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register('bank', views.BankViewSet)
router.register('bank_account', views.BankAccountViewSet)
router.register('client', views.ClientViewSet)
router.register('transaction', views.TransactionViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('', views.homepage, name='homepage'),
    path('banks/', views.BankListView.as_view(), name='banks'),
    path('clients/', views.clients_view, name='clients'),
    path('banks/<uuid:pk>/', views.BankDetailView.as_view(), name='bank_detail'),
    path('clients/<uuid:pk>/', views.ClientDetailView.as_view(), name='client_detail'),
    path('profile/', views.profile_view, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path(
        'delete_bank_account/<uuid:pk>/',
        views.delete_bank_account_view, name='delete_bank_account',
    ),
    path('create_bank_account/', views.create_bank_account_view, name='create_bank_account'),
    path('bank_accounts/', views.bank_accounts_view, name='bank_accounts'),
    path(
        'transactions/<uuid:pk>/',
        views.TransactionDetailView.as_view(),
        name='transaction_detail',
    ),
    path('user_transactions/', views.UserTransactionListView.as_view(), name='user_transactions'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.register_view, name='register'),
    path('create_client/', views.create_client, name='create_client'),
    path('create_bank/', views.create_bank_view, name='create_bank'),
    path('delete_bank/<uuid:pk>/', views.delete_bank_view, name='delete_bank'),
    path('create_transaction/', views.create_transaction, name='create_transaction'),
    path('confirm_transaction/', views.confirm_transaction, name='confirm_transaction'),
    path('transactions/', views.transactions_view, name='transactions'),
    path(
        'delete_transaction/<uuid:pk>/',
        views.delete_transaction_view,
        name='delete_transaction',
    ),
]

banks_app/models.py
"""
This module contain models for banking system.

It includes models for Bank, Client, BankAccount, Transaction and their interrelationships.
"""

from datetime import datetime
from decimal import Decimal
from uuid import uuid4

import django.core.validators as validators
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from banks_app import config


def get_datetime() -> datetime:
    """
    Get the current date and time.

    Returns:
        datetime: The current date and time.
    """
    return timezone.now().date()


def check_created(dt: datetime) -> None:
    """
    Check if the provided datetime is in the future.

    Args:
        dt (datetime): The datetime to check.

    Raises:
        ValidationError: If the provided datetime is in the future.
    """
    if dt > timezone.now().date():
        raise ValidationError(
            _('Date and time is bigger than current!'),
            params={'created': dt},
        )


class UUIDMixin(models.Model):
    """
    Abstract model mixin for UUID primary key.

    Attributes:
        id (UUIDField): Primary key, automatically generated.
    """

    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    class Meta:
        """Meta class for UUIDMixin."""

        abstract = True


class Bank(UUIDMixin):
    """
    Model represent a bank.

    Attributes:
        title (str): The name of the bank.
        foundation_date (datetime): The date the bank was founded.
        clients (ManyToManyField): The clients associated with the bank.
    """

    title = models.CharField(
        max_length=100,
        validators=[
            validators.MaxLengthValidator(
                100, message='Length title must be less than 100 symbols',
            ),
            validators.MinLengthValidator(
                1, message='Length title must be more than 0 symbol',
            ),
        ],
        unique=True,
    )

    foundation_date = models.DateField(default=get_datetime, validators=[check_created])

    clients = models.ManyToManyField('Client', through='BankClient', verbose_name=_('clients'))

    class Meta:
        """Meta class for model Bank."""

        db_table = '"banks"."bank"'
        verbose_name = _('bank')
        verbose_name_plural = _('banks')

    def __str__(self) -> str:
        """Magic method for displaying short information about Bank.

        Returns:
            str: Short information about Bank.
        """
        return f'Bank: "{self.title}", foundation_date: {self.foundation_date}'


class Client(UUIDMixin):
    """
    Model represent a client.

    Attributes:
        user (OneToOneField): The user associated with the client.
        first_name (str): The first name of the client.
        last_name (str): The last name of the client.
        phone (str): The phone number of the client.
        banks (ManyToManyField): The banks associated with the client.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(
        max_length=config.MAX_LENGTH_FIRST_NAME,
        validators=[
            validators.MaxLengthValidator(
                config.MAX_LENGTH_FIRST_NAME,
                message='Length first_name must be less than 70 symbols',
            ),
            validators.MinLengthValidator(
                1, message='Length first_name must be more than 0 symbol',
            ),
        ],
    )
    last_name = models.CharField(
        max_length=config.MAX_LENGTH_LAST_NAME,
        validators=[
            validators.MaxLengthValidator(
                config.MAX_LENGTH_LAST_NAME,
                message='Length last_name must be less than 100 symbols',
            ),
            validators.MinLengthValidator(
                1, message='Length last_name must be more than 0 symbol',
            ),
        ],
    )
    phone_regex = validators.RegexValidator(
        regex=r'\+7\d{10}', message='Phone number must be 10 digits in total.',
    )
    phone = models.CharField(max_length=config.MAX_LENGTH_PHONE, validators=[phone_regex])

    banks = models.ManyToManyField('Bank', through='BankClient', verbose_name=_('banks'))

    class Meta:
        """Meta class for model Client."""

        db_table = '"banks"."client"'
        verbose_name = _('client')
        verbose_name_plural = _('clients')

    def __str__(self) -> str:
        """Magic method for displaying short information about Client.

        Returns:
            str: Short information about Client.
        """
        return f'Client: {self.first_name} {self.last_name}, phone: {self.phone}'


class BankClient(UUIDMixin):
    """
    Model represent the relationship between a bank and a client.

    Attributes:
        bank (ForeignKey): The bank in the relationship.
        client (ForeignKey): The client in the relationship.
    """

    bank = models.ForeignKey('Bank', verbose_name=_('bank'), on_delete=models.CASCADE)
    client = models.ForeignKey('Client', verbose_name=_('client'), on_delete=models.CASCADE)

    class Meta:
        """Meta class for model BankClient."""

        db_table = '"banks"."bank_client"'
        unique_together = (
            ('bank', 'client'),
        )
        verbose_name = _('relationship bank client')
        verbose_name_plural = _('relationships bank client')

    def __str__(self) -> str:
        """Magic method for displaying information about BankClient.

        Returns:
            str: Information about BankClient.
        """
        return f'{self.bank} - {self.client}'


class BankAccount(UUIDMixin):
    """
    Model represent a bank account.

    Attributes:
        balance (DecimalField): The balance of the bank account.
        bank (ForeignKey): The bank associated with the account.
        client (ForeignKey): The client associated with the account.
    """

    balance = models.DecimalField(
        decimal_places=2, max_digits=config.MAX_DIGITS_BANK_ACCOUNT,
        validators=[validators.MinValueValidator(Decimal('0.00'))],
    )
    bank = models.ForeignKey(Bank, verbose_name=_('bank'), on_delete=models.CASCADE)
    client = models.ForeignKey(Client, verbose_name=_('client'), on_delete=models.CASCADE)

    class Meta:
        """Meta class for model BankAccount."""

        db_table = '"banks"."bank_account"'
        verbose_name = _('bank_account')
        verbose_name_plural = _('bank_accounts')

    def __str__(self) -> str:
        """Magic method for displaying short information about BankAccount.

        Returns:
            str: Short information about BankAccount.
        """
        return f'Bank_account: {self.id}, balance: {self.balance}'


class Transaction(UUIDMixin):
    """
    Model represent a transaction.

    Attributes:
        initializer (ForeignKey): The client who initiated the transaction.
        amount (DecimalField): The amount of the transaction.
        transaction_date (DateField): The date of the transaction.
        description (str): The description of the transaction.
        from_bank_account_id (ForeignKey): The source bank account.
        to_bank_account_id (ForeignKey): The destination bank account.
    """

    initializer = models.ForeignKey(Client, on_delete=models.RESTRICT, related_name='initializer')

    amount = models.DecimalField(
        decimal_places=2,
        max_digits=config.MAX_DIGITS_AMOUNT,
        validators=[validators.MinValueValidator(Decimal('0.00'))],
    )

    transaction_date = models.DateField(default=get_datetime, validators=[check_created])

    description = models.CharField(
        null=True,
        blank=True,
        max_length=config.MAX_LENGTH_DESCRIPTION,
        validators=[
            validators.MaxLengthValidator(
                config.MAX_LENGTH_DESCRIPTION,
                message='Length description must be less than 500 symbols',
            ),
        ],
    )
    from_bank_account_id = models.ForeignKey(
        BankAccount,
        on_delete=models.CASCADE,
        related_name='sent_transactions',
    )
    to_bank_account_id = models.ForeignKey(
        BankAccount,
        on_delete=models.CASCADE,
        related_name='received_transactions',
    )

    class Meta:
        """Meta class for model Transaction."""

        db_table = '"banks"."transaction"'
        verbose_name = _('transaction')
        verbose_name_plural = _('transactions')

    def __str__(self) -> str:
        """Magic method for displaying information about Transaction.

        Returns:
            str: Information about Transaction.
        """
        return f"Initializer: {self.initializer}, amount: {self.amount}," \
               f"description: {self.description}," \
               f"from: {self.from_bank_account_id}, to: {self.to_bank_account_id}"


class TransactionClient(UUIDMixin):
    """
    Model represent the relationship between a transaction and a client.

    Attributes:
        client (ForeignKey): The client in the relationship.
        transaction (ForeignKey): The transaction in the relationship.
    """

    client = models.ForeignKey(Client, verbose_name=_('client'), on_delete=models.CASCADE)
    transaction = models.ForeignKey(
        Transaction, verbose_name=_('transaction'), on_delete=models.CASCADE,
    )

    class Meta:
        """Meta class for model TransactionClient."""

        db_table = '"banks"."transaction_client"'
        unique_together = (
            ('transaction', 'client'),
        )
        verbose_name = _('relationship transaction client')
        verbose_name_plural = _('relationships transaction client')

    def __str__(self) -> str:
        """Magic method for displaying information about TransactionClient.

        Returns:

banks_app/forms.py
"""Forms configuration for the banks_app."""

from django import forms
from django.contrib.auth.models import User

from banks_app import config

from .models import Bank, BankAccount, Client, Transaction


class UserRegistrationForm(forms.ModelForm):
    """Form for user registration."""

    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        """Meta class for UserRegistrationForm."""

        model = User
        fields = ['username', 'password']

    def save(self, commit=True):
        """
        Save the new user instance with an encrypted password.

        Args:
            commit (bool): If True, the user instance is saved to the database.

        Returns:
            User: The newly created user instance.
        """
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class BankAccountForm(forms.ModelForm):
    """Form for managing bank account information."""

    class Meta:
        """Meta class for BankAccountForm."""

        model = BankAccount
        fields = ['balance', 'bank']


class ClientForm(forms.ModelForm):
    """Form for managing client information."""

    banks = forms.ModelMultipleChoiceField(
        queryset=Bank.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        """Meta class for ClientForm."""

        model = Client
        fields = ['first_name', 'last_name', 'phone', 'banks']


class BankForm(forms.ModelForm):
    """Form for managing bank information."""

    class Meta:
        """Meta class for BankForm."""

        model = Bank
        fields = ['title', 'foundation_date']


class LoginForm(forms.Form):
    """Form for user login."""

    username = forms.CharField(max_length=config.MAX_LENGTH_USERNAME)
    password = forms.CharField(
        max_length=config.MIN_LENGTH_USERNAME, widget=forms.PasswordInput,
    )


class ConfirmTransactionForm(forms.ModelForm):
    """Form for confirming a transaction."""

    class Meta:
        """Meta class for ConfirmTransactionForm."""

        model = Transaction
        fields = ['amount', 'description', 'transaction_date']
        widgets = {
            'transaction_date': forms.DateInput(attrs={'type': 'date'}),
        }


class InitialTransactionForm(forms.Form):
    """Form for initiating a transaction."""

    from_bank_account_id = forms.ModelChoiceField(
        queryset=BankAccount.objects.none(),
        label='Select your bank account',
    )
    to_bank_account_uuid = forms.UUIDField(
        label='Recipient Bank Account UUID',
    )

    def __init__(self, *args, **kwargs):
        """
        Initialize the form with user-specific bank accounts.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        user = kwargs.pop('user', None)
        super(InitialTransactionForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['from_bank_account_id'].queryset = BankAccount.objects.filter(
                client__user=user,
            )

banks_app/templates/pages/bank_accounts.html
{% extends "base_generic.html" %}

{% block title %}
<title>Bank Accounts</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Bank Accounts</h1>
    <ul class="list-group">
        {% for bank_account in bank_accounts %}
        <li class="list-group-item mb-3">
            <p><strong>Bank_account_id:</strong> {{ bank_account.id }}</p>
            <p><strong>Balance:</strong> {{ bank_account.balance }}</p>
            <p><strong>Bank:</strong> {{ bank_account.bank.title }}</p>
            <div class="mt-2">
                <form method="get" action="{% url 'bank_detail' bank_account.bank.id %}"
                    class="d-inline-block mb-2 mr-2">
                    <button type="submit" class="btn btn-primary btn-sm">View Bank Details</button>
                </form>
                {% if request.user.is_superuser %}
                <form method="post" action="{% url 'delete_bank_account' bank_account.id %}?next={{ request.path }}"
                    class="d-inline-block">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Delete Bank Account</button>
                </form>
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

banks_app/templates/pages/bank_detail.html
{% extends "base_generic.html" %}

{% block title %}
<title>{{ bank.title }} Details</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">{{ bank.title }}</h1>
    <p><strong>Foundation Date:</strong> {{ bank.foundation_date }}</p>
    <h2>Clients</h2>
    <ul class="list-group">
        {% for client in bank.clients.all %}
        <li class="list-group-item">{{ client.first_name }} {{ client.last_name }} ({{ client.phone }})</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

banks_app/templates/pages/banks.html
{% extends "base_generic.html" %}

{% block title %}
<title>Banks</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Banks</h1>
    {% if request.user.is_superuser %}
    <a href="{% url 'create_bank' %}" class="btn btn-success mb-3">Add Bank</a>
    {% endif %}
    <ul class="list-group">
        {% for bank in banks %}
        <li class="list-group-item mb-3">
            <p><strong>Title:</strong> {{ bank.title }}</p>
            <p><strong>Foundation Date:</strong> {{ bank.foundation_date }}</p>
            <div class="mt-2">
                <form method="get" action="{% url 'bank_detail' bank.id %}" class="d-inline-block mb-2 mr-2">
                    <button type="submit" class="btn btn-primary btn-sm">View Details</button>
                </form>
                {% if request.user.is_superuser %}
                <form method="post" action="{% url 'delete_bank' bank.id %}?next={{ request.path }}"
                    class="d-inline-block">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Delete Bank</button>
                </form>
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

banks_app/templates/pages/client_detail.html
{% extends "base_generic.html" %}

{% block title %}
<title>{{ client.first_name }} {{ client.last_name }} Details</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">{{ client.first_name }} {{ client.last_name }}</h1>
    <p><strong>Phone:</strong> {{ client.phone }}</p>
    <h2>Banks</h2>
    <ul class="list-group">
        {% for bank in client.banks.all %}
        <li class="list-group-item">{{ bank.title }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

banks_app/templates/pages/clients.html
{% extends "base_generic.html" %}

{% block title %}
<title>Clients</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Clients</h1>

    <ul class="list-group">
        {% for client in clients %}
        <li class="list-group-item mb-3">
            <p><strong>Username:</strong> {{ client.user.username }}</p>
            <p><strong>First Name:</strong> {{ client.first_name }}</p>
            <p><strong>Last Name:</strong> {{ client.last_name }}</p>
            <p><strong>Phone:</strong> {{ client.phone }}</p>
            <div class="mt-2">
                {% if request.user.is_superuser %}
                <form method="get" action="{% url 'client_detail' client.id %}" class="d-inline-block mb-2 mr-2">
                    <button type="submit" class="btn btn-primary btn-sm">View Details</button>
                </form>
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

banks_app/templates/pages/confirm_transaction.html
<!-- templates/pages/confirm_transaction.html -->

{% extends "base_generic.html" %}

{% block title %}
<title>Confirm Transaction</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Confirm Transaction</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">From Bank Account:</label>
            <p>{{ from_account.id }}</p>
        </div>
        <div class="mb-3">
            <label class="form-label">To Bank Account:</label>
            <p>{{ to_account.id }}</p>
        </div>
        <div class="mb-3">
            <label for="id_amount" class="form-label">Amount</label>
            {{ form.amount }}
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">Description</label>
            {{ form.description }}
        </div>
        <div class="mb-3">
            <label for="id_transaction_date" class="form-label">Transaction Date</label>
            {{ form.transaction_date }}
        </div>
        <button type="submit" class="btn btn-primary">Confirm Transaction</button>
    </form>
</div>
{% endblock %}

banks_app/templates/pages/create_bank.html
{% extends "base_generic.html" %}

{% block title %}
<title>Create Bank</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Create Bank</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create Bank</button>
    </form>
</div>
{% endblock %}

banks_app/templates/pages/create_bank_account.html
{% extends "base_generic.html" %}

{% block title %}
<title>Create Bank Account</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Create Bank Account</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create Bank Account</button>
    </form>
</div>
{% endblock %}

banks_app/templates/pages/create_client.html
{% extends "base_generic.html" %}

{% block title %}
<title>Create Client</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Create Client Profile</h1>
    <form method="post" action="{% url 'create_client' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

banks_app/templates/pages/create_transaction.html
<!-- templates/pages/create_transaction.html -->

{% extends "base_generic.html" %}

{% block title %}
<title>Create Transaction</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Create New Transaction</h1>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_from_bank_account_id" class="form-label">Select your bank account</label>
            {{ form.from_bank_account_id }}
        </div>
        <div class="mb-3">
            <label for="id_to_bank_account_uuid" class="form-label">Recipient Bank Account UUID</label>
            {{ form.to_bank_account_uuid }}
        </div>
        <button type="submit" class="btn btn-primary">Next</button>
    </form>
</div>
{% endblock %}

banks_app/templates/pages/profile.html
{% extends "base_generic.html" %}

{% block title %}
<title>Profile</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">User Profile</h1>
    <p><strong>Username:</strong> {{ client.user.username }}</p>
    <p><strong>First Name:</strong> {{ client.first_name }}</p>
    <p><strong>Last Name:</strong> {{ client.last_name }}</p>
    <p><strong>Phone:</strong> {{ client.phone }}</p>

    <h2>Banks:</h2>
    <ul class="list-group">
        {% for bank in banks %}
        <li class="list-group-item mb-3">
            <p><strong>Title:</strong> {{ bank.title }}</p>
            <p><strong>Foundation Date:</strong> {{ bank.foundation_date }}</p>
            <div class="mt-2">
                <form method="get" action="{% url 'bank_detail' bank.id %}" class="d-inline-block mb-2 mr-2">
                    <button type="submit" class="btn btn-primary btn-sm">View Details</button>
                </form>
            </div>
        </li>
        {% endfor %}
    </ul>

    <h2>Bank Accounts:</h2>
    <ul class="list-group">
        {% for bank_account in bank_accounts %}
        <li class="list-group-item mb-3">
            <p><strong>ID:</strong> {{ bank_account.id }}</p>
            <p><strong>Balance:</strong> {{ bank_account.balance }}</p>
            <p><strong>Bank:</strong> {{ bank_account.bank.title }}</p>
            <div class="mt-2">
                <form method="get" action="{% url 'bank_detail' bank_account.bank.id %}"
                    class="d-inline-block mb-2 mr-2">
                    <button type="submit" class="btn btn-primary btn-sm">View Bank Details</button>
                </form>
                <form method="post" action="{% url 'delete_bank_account' bank_account.id %}?next={{ request.path }}"
                    class="d-inline-block">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Delete Bank Account</button>
                </form>
            </div>
        </li>
        {% endfor %}
    </ul>

    <div class="mt-5">
        <a class="btn btn-primary" href="{% url 'create_bank_account' %}">Add New Bank Account</a>
    </div>

    <h2>Transactions:</h2>
    <ul class="list-group">
        {% for transaction in transactions %}
        <li class="list-group-item mb-3">
            <p><strong>Amount:</strong> {{ transaction.amount }}</p>
            <p><strong>Date:</strong> {{ transaction.transaction_date }}</p>
            <p><strong>Description:</strong> {{ transaction.description }}</p>
            <div class="mt-2">
                <form method="get" action="{% url 'transaction_detail' transaction.id %}"
                    class="d-inline-block mb-2 mr-2">
                    <button type="submit" class="btn btn-primary btn-sm">View Transaction Details</button>
                </form>
            </div>
        </li>
        {% endfor %}
    </ul>

    <div class="mt-5">
        <a class="btn btn-primary" href="{% url 'create_transaction' %}">Add New Transaction</a>
    </div>
</div>
{% endblock %}

banks_app/templates/pages/transaction_detail.html
{% extends "base_generic.html" %}

{% block title %}
<title>Transaction Detail</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5">Transaction Detail</h1>
    <p><strong>ID:</strong> {{ transaction.id }}</p>
    <p><strong>Initializer:</strong> {{ transaction.initializer }}</p>
    <p><strong>Amount:</strong> {{ transaction.amount }}</p>
    <p><strong>Date:</strong> {{ transaction.transaction_date }}</p>
    <p><strong>Description:</strong> {{ transaction.description }}</p>
    <p><strong>From:</strong> {{ transaction.from_bank_account_id.id }}</p>
    <p><strong>To:</strong> {{ transaction.to_bank_account_id.id }}</p>
</div>
{% endblock %}

banks_app/templates/pages/transactions.html
{% extends "base_generic.html" %}

{% block title %}
<title>Transactions</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Transactions</h1>
    <ul class="list-group">
        {% for transaction in transactions %}
        <li class="list-group-item mb-3">
            <p><strong>Transaction ID:</strong> {{ transaction.id }}</p>
            <p><strong>Amount:</strong> {{ transaction.amount }}</p>
            <p><strong>Description:</strong> {{transaction.description }}</p>
            <p><strong>From:</strong> {{ transaction.from_bank_account_id }}</p>
            <p><strong>To:</strong> {{transaction.to_bank_account_id }}</p>
            <p><strong>Date:</strong> {{ transaction.transaction_date }}</p>
            <div class="mt-2">
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

banks_app/templates/pages/user_transactions.html
{% extends "base_generic.html" %}

{% block title %}
<title>User Transactions</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-5">User Transactions</h1>
    <ul>
        {% for transaction in transactions %}
        <li>{{ transaction }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}